const products=[
    {
        id: 1,
        name:'Toyata',
        price: 1000,
        instock: 5,
        description: 'This is a toyata car',
        imgSrc: './img/mitsubisi.jpg',
    },
    {
        id: 2,
        name:'mitsubisi',
        price: 2000,
        instock: 7,
        description: 'This is a mitsubisi car',
        imgSrc: './img/toyota.jpg',
    },
    {
        id: 3,
        name:'corolla',
        price: 1500,
        instock: 3,
        description: 'This is a corolla car',
        imgSrc: './img/corolla.jpg',
    },
    {
        id: 4,
        name:'Toyata',
        price: 1000,
        instock: 200,
        description: 'This is a toyata car',
        imgSrc: './img/mitsubisi.jpg',
    },
    {
        id: 5,
        name:'mitsubisi Plus',
        price: 2000,
        instock: 500,
        description: 'This is a mitsubisi Plus car',
        imgSrc: './img/toyota.jpg',
    },
    {
        id: 6,
        name:'X-corolla',
        price: 5000,
        instock: 50,
        description: 'This is a X-corolla car',
        imgSrc: './img/corolla.jpg',
    },
]